baseURL = 'https://cdn.fryrvo.com/'
locale = 'en-us'
title = 'Fryrvo CDN Server'
theme = "PaperMod"

[params]
  env = 'production'
  title = 'Asset CDN'
  description = 'cdn'
  
[params.homeInfoParams]
 Title = "CDN"
 Content = """
 Welcome to the CDN. Access files directly via /filename.png
 """
 
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[params.socialIcons]]
 name = "github"
 url = "https://github.com/Fryrvo"

[[params.socialIcons]]
 name = "website"
 url = "https://fryrvo.com"

[[params.socialIcons]]
 name = "email"
 url = "mailto:contact@fryrvo.com"

[[params.socialIcons]]
 name = "discord"
 url = "https://fryrvo.com/discord"


[[menus.main]]
  name = "Documentation"
  url = "/file.html"
  weight = 10

[[menus.main]]
  name = "Status"
  url = "https://status.fryrvo.com"
  weight = 20